//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purshare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purshare()
        {
            this.PurshareProduct = new HashSet<PurshareProduct>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int StaffId { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurshareProduct> PurshareProduct { get; set; }
    }
}
