//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurshareProduct
    {
        public int Id { get; set; }
        public int PurshareId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Purshare Purshare { get; set; }
    }
}
